import { Injectable } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import type { DocumentParams } from '../mail/templates/document.js';

/**
 * Renders the same DocumentParams the email templates use into a real PDF,
 * so every invoice and receipt email carries a file the recipient can save,
 * print, or hand to an accountant. Email HTML is not a document — the
 * attachment is.
 */
@Injectable()
export class DocumentPdfService {
  render(doc: DocumentParams): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const pdf = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];
      pdf.on('data', (c: Buffer) => chunks.push(c));
      pdf.on('end', () => resolve(Buffer.concat(chunks)));
      pdf.on('error', reject);

      const money = (v: number) =>
        `${doc.currency} ${v.toLocaleString('en-KE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
      const left = 50;
      const right = 545;

      // ── Masthead ──
      pdf.fontSize(20).font('Helvetica-Bold').fillColor('#111112').text('e-resi', left, 50);
      pdf.fontSize(9).font('Helvetica').fillColor('#6b6b70')
        .text('Immersive real estate · e-resi.com', left, 74);

      pdf.fontSize(16).font('Helvetica-Bold').fillColor('#111112')
        .text(doc.heading.toUpperCase(), left, 50, { align: 'right', width: right - left });
      pdf.fontSize(10).font('Helvetica').fillColor('#6b6b70')
        .text(doc.number, left, 72, { align: 'right', width: right - left });

      // ── Billed to + meta ──
      let y = 115;
      pdf.moveTo(left, y).lineTo(right, y).strokeColor('#e4e4e7').lineWidth(1).stroke();
      y += 14;

      pdf.fontSize(8).font('Helvetica-Bold').fillColor('#8a8a90').text('BILLED TO', left, y);
      pdf.fontSize(10).font('Helvetica').fillColor('#111112')
        .text(doc.billedToName, left, y + 12)
        .text(doc.billedToEmail, left, y + 26);

      let metaY = y;
      for (const m of doc.meta) {
        pdf.fontSize(8).font('Helvetica-Bold').fillColor('#8a8a90')
          .text(m.label.toUpperCase(), 330, metaY, { width: 90 });
        pdf.fontSize(9).font('Helvetica').fillColor('#111112')
          .text(m.value, 420, metaY - 1, { width: right - 420, align: 'right' });
        metaY += 16;
      }

      y = Math.max(y + 48, metaY + 10);

      // ── Lines table ──
      pdf.rect(left, y, right - left, 22).fill('#f4f4f5');
      pdf.fontSize(8).font('Helvetica-Bold').fillColor('#6b6b70');
      pdf.text('DESCRIPTION', left + 10, y + 7, { width: 280 });
      pdf.text('QTY', 350, y + 7, { width: 40, align: 'right' });
      pdf.text('AMOUNT', 420, y + 7, { width: right - 430, align: 'right' });
      y += 22;

      pdf.font('Helvetica').fontSize(9.5).fillColor('#111112');
      for (const line of doc.lines) {
        const h = Math.max(
          pdf.heightOfString(line.description, { width: 280 }) + 12,
          24,
        );
        pdf.fillColor('#111112').text(line.description, left + 10, y + 6, { width: 280 });
        pdf.fillColor('#6b6b70').text(String(line.quantity ?? 1), 350, y + 6, { width: 40, align: 'right' });
        pdf.fillColor('#111112').text(money(line.amount), 420, y + 6, { width: right - 430, align: 'right' });
        y += h;
        pdf.moveTo(left, y).lineTo(right, y).strokeColor('#f0f0f2').lineWidth(0.5).stroke();
      }

      // ── Totals ──
      y += 10;
      const totalRow = (label: string, value: string, bold = false) => {
        pdf.fontSize(bold ? 11 : 9.5)
          .font(bold ? 'Helvetica-Bold' : 'Helvetica')
          .fillColor(bold ? '#111112' : '#6b6b70')
          .text(label, 330, y, { width: 120 });
        pdf.fillColor('#111112').text(value, 420, y, { width: right - 420, align: 'right' });
        y += bold ? 20 : 16;
      };
      totalRow('Subtotal', money(doc.subtotal));
      if (doc.taxAmount > 0) totalRow(`VAT (${doc.taxPercent}%)`, money(doc.taxAmount));
      totalRow('Total', money(doc.total), true);

      // ── Callout / footnote ──
      if (doc.callout) {
        y += 8;
        pdf.fontSize(9).font('Helvetica').fillColor('#1a7d43')
          .text(doc.callout.text, left, y, { width: right - left });
        y += 18;
      }
      if (doc.footnote) {
        y += 6;
        pdf.fontSize(8).font('Helvetica').fillColor('#8a8a90')
          .text(doc.footnote, left, y, { width: right - left });
      }

      pdf.fontSize(8).fillColor('#b9b9be')
        .text('Generated by e-resi · This document was issued electronically and is valid without a signature.',
          left, 780, { width: right - left, align: 'center' });

      pdf.end();
    });
  }
}
